-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgU2j+Cw/SsUB1Gohj
MZG3RHiF3Xex40D4Z1YEmxnVEKOgCgYIKoZIzj0DAQehRANCAASAcZYyhYXF+jjr
gdjD+EGulaQ+qgvNd6V4BdTZBQ2YnfPpjKynboSh10MCe79GZGpR9ERsc+8h4F49
gbUSaNtg
-----END PRIVATE KEY-----